### ISSUE TITLE
Running Freeview core dumps

### ISSUE THREAD

**Issue by pwighton** [NeuroDesk/vnm#66] opened 2020-07-07 17:12 UTC
I'm getting a core dump when trying to execute Freeview.

After running:
```
mkdir -p ~/vnm
sudo docker run --privileged -e USER=neuro -e PASSWORD=neuro --name vnm -v ~/vnm:/vnm -p 6080:80 vnmd/vnm:latest
```

Then browsing to `http://localhost:6080/` and clicking start->VNM Neuroimaging->FreeSurfer->FreeSurfer 7.1.0 drops me into a sigularity container.  

Running `freeview` in that shell gives the following error: https://imgur.com/a/ZQlo4lA

```
you are now inside the container freesurfer_7.1.0_20200702
Singularity> freeview 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-neuro'
process 2152: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should container a hex string of length 32, not length 0, with no other text
```

System info
```
(base) paul@paul-xps-15:~$ docker --version
Docker version 18.09.0, build 4d60db4
(base) paul@paul-xps-15:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```
This is a very excited project!  A lot of folks would love to see an easy-to-use, browser-based solution for freeview!  Happy to try to get this working if I could get pointed in the right direction.

**Comment by stebo85** [comment] 2020-07-08 01:02
Dear @pwighton,

Thank you so much for finding this bug :) It got introduced when we switched from building our containers in singularity directly to building them in docker via github actions last week. Somehow docker messes with this UUID file '/etc/machine-id' which causes the problem you are seeing. I can reproduce the problem and I am trying to fix it now :)

Thank you!
Cheers
Steffen

**Comment by stebo85** [comment] 2020-07-08 01:08
trying different solutions right now, if anyone has an idea, please add:
people suggest to try:
- ln -s /var/lib/dbus/machine-id /etc/machine-id
- installing systemd

**Comment by stebo85** [comment] 2020-07-08 06:05
I found a fix and it is already working in the devlelopment version. Currently the container is rebuilding on docker-hub - then I will test that one and then we should be able to close this issue :)

**Comment by stebo85** [comment] 2020-07-08 12:00
Dear @pwighton,

The latest vnm version has a working freeview version again :) Since you already downloaded a freesurfer container you need to remove this container and redownload the updated version - the tag is 20200708

![image](https://user-images.githubusercontent.com/4021595/86915879-0ef53f80-c166-11ea-9a3f-72a38d0570e3.png)

does this work for you as well?

Please keep testing more things - it's difficult to find bugs like this because we haven't found a way of automatically testing the graphical applications in our containers

**Comment by pwighton** [comment] 2020-07-08 17:17
Thanks @stebo85!  I can confirm this is working on my end. :)

I'll keep playing around with things and report any problems I come across.

**Comment by stebo85** [comment] 2020-07-08 23:34
Thank you @pwighton for confirming :) 

Yes, reporting more issues would be great! The more feedback we get in these early steps of the project the better :) Please also feel free to open issues for improvements and features you would be keen to see.

Cheers
Steffen

**Closed by stebo85** 2020-07-08 23:34 UTC
