### ISSUE TITLE
Modules don't work on Ubuntu 18.04 LTS VM on OpenStack

### ISSUE THREAD

**Issue by civier** [NeuroDesk/vnm#44] opened 2020-06-26 22:37 UTC
When I try to run "ml avail" I get this error:
```
Lmod has detected the following error:  avail is not possible,
MODULEPATH is not set or not set with valid paths.
```
From what I see, /vnm/modules does not exist. Are you still working on it or somethings is missing in the installation?
Oren

**Comment by stebo85** [comment] 2020-06-27 23:32
Dear @civier,

What docker command did you use the run the container? 

My first guess would be that there is no persistent folder mounted inside, so it was started without this parameter:
-v /path/to/persistent:/vnm

If that is the case do you think we should detect that automatically and create a non-persistent folder?

Best
Steffen

**Comment by stebo85** [comment] 2020-06-27 23:49
I now modified the quickstart instructions to include the correct mount-points (it was in the detailed instructions further below, but people might not read that far)

@meganEJcampbell : can you test if the mac instructions work?
docker run --privileged -e USER=neuro -e PASSWORD=neuro --name vnm -v ~/vnm:/vnm -p 6080:80 vnmd/vnm:latest

**Comment by stebo85** [comment] 2020-06-29 07:11
Dear @civier - can you confirm if this was the actual problem and if it solved it :? I hope it's not another bug, because then I currently cannot reproduce it. Would you have more detail how to get this error?

**Comment by meganEJcampbell** [comment] 2020-06-29 07:23
> I now modified the quickstart instructions to include the correct mount-points (it was in the detailed instructions further below, but people might not read that far)
> 
> @meganEJcampbell : can you test if the mac instructions work?
> docker run --privileged -e USER=neuro -e PASSWORD=neuro --name vnm -v ~/vnm:/vnm -p 6080:80 vnmd/vnm:latest

@stebo85 trying now, and it's succesfully downloaded all the bits, but is stuck with at: 
Listening on http://localhost:6079 (run.py:87)
nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
(same for web, xvfb, wm, lxpanel, pcmanfm, x11vnc, and novnc) 

I'm gonna leave it thinking and can confirm tomorrow if it worked. (unfortunately i've gotta scoot and can hang about to see if it works), but given the first time I tried an install during the hackathon it worked with minutes I'd say something is not right....?
P.S. I like your edits to the instructions - N00bs will keep reading but wizards can just read the bit they need on top ;) best of both!

**Comment by stebo85** [comment] 2020-06-29 07:26
Hi @meganEJcampbell:  This all looks good. What happens when you do step 4 and open your browser and go http://localhost:6080 :?

**Comment by meganEJcampbell** [comment] 2020-06-29 07:40
Ah my level of N00bness is extreme 🥇 hahaha! step 4 worked. tried on Mozilla firefox, chrome and safari and all good for all three, in case that matters. :-)

**Comment by stebo85** [comment] 2020-06-29 07:47
Cool :) @meganEJcampbell, other things to test would be: can you start a tool from the menu (like itksnap)? I guess step 4 is not clear, what can be improved to make that clearer :?

**Comment by meganEJcampbell** [comment] 2020-06-29 07:57
I've committed some edits to the readme :-) I'll try to run some tools tomorrow. Cheers!

**Comment by meganEJcampbell** [comment] 2020-06-30 06:45
> Cool :) @meganEJcampbell, other things to test would be: can you start a tool from the menu (like itksnap)? I guess step 4 is not clear, what can be improved to make that clearer :?

Success in opening itksnap but it's glitchy in that the display windows overlap eachother (see screenshot), and I can't use the iksnap gui for anything (clicking on things and nothing happens)... That's probably a connection speed issue though right? although i'm on ethernet network with 115.2+ Mbps download and 63.46 Mbps upload... 
![Screen Shot 2020-06-30 at 4 38 00 pm](https://user-images.githubusercontent.com/34408937/86092118-62291b80-baf0-11ea-84f8-308991b257e7.png)

**Comment by meganEJcampbell** [comment] 2020-06-30 06:48
> Cool :) @meganEJcampbell, other things to test would be: can you start a tool from the menu (like itksnap)? I guess step 4 is not clear, what can be improved to make that clearer :?

small thing - I don't htink I'm closing the doker properly ... is there a step before typing >docker stop vnm into terminal? I've closed the browser window but my terminal is still running the things and doesn't execute the new command to "stop"

**Comment by stebo85** [comment] 2020-07-01 08:10
@meganEJcampbell - Thank you so much for testing! The glitch you are seeing in ITKsnap is interesting. It's not a connection issue, because the container runs on your own computer. Can you check if there is a warning in the background that blocks you from using itk? I have an idea how to fix this otherwise!

closing the container: Yes, this is not yet userfriendly and you need to press CTRL-C in the terminal where you ran the docker command. Does this give you back the control and can you then type stop?

**Comment by stebo85** [comment] 2020-07-02 23:58
@meganEJcampbell I hope I fixed the itksnap problems in the current master branch :) Can you test again?
@civier since you haven't reported back on your problem I am assuming it's fixed and close that issue for now - please open a new issue if it's still a problem for you :)

**Closed by stebo85** 2020-07-02 23:58 UTC
